apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  immutable: false
data: 
   username: admin
   mongodb.config: |
      storage: 
         dbpath: /data/configdb
      replication:
          replSetName: "rs0"