apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  # we don't give any ip type it will choose ClusterIp
  selector:
    app: nginx
  ports:
    - port: 8082
      targetPort: 80
      nodePort: 30000