apiVersion: v1
kind: deployment
metadata:
  name: nginx-deployment
  namespace: nginx-namespace
spec:
  replicas:5
  selectors:
    matchLables:
      app: nginx
  template:
    metadata:
      - name: nginx-pod
        lables:
          app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
             - containerPort: 80


