# As we discussed to talk a specific pod we need a headless service.

apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
    - name: mongo
    - ports:
        port: 27017
        targetPort: 27017
  clusterIp: None
  selector:
     app: mongo



